name: CI

on: push

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar testes
        run: pytest
        